# Project: ScreenSaver
# Makefile created by Dev-C++ 5.2.0.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o sources/MatrixScreenSaver/graphics/graphics.o sources/MatrixScreenSaver/sound/sounds.o sources/ScreenSaverShell/Shell.o $(RES)
LINKOBJ  = main.o sources/MatrixScreenSaver/graphics/graphics.o sources/MatrixScreenSaver/sound/sounds.o sources/ScreenSaverShell/Shell.o $(RES)
LIBS     = -L"F:/IDE/Dev-Cpp/Base/MinGW32/lib" -static-libstdc++ -static-libgcc -mwindows ../../../../../IDE/Dev-Cpp/Base/MinGW32/lib/libwinmm.a ../../../../../IDE/Dev-Cpp/Base/MinGW32/lib/libuser32.a  -s 
INCS     = -I"F:/IDE/Dev-Cpp/Base/MinGW32/include" 
CXXINCS  = -I"F:/IDE/Dev-Cpp/Base/MinGW32/include" 
BIN      = ScreenSaver.exe
CXXFLAGS = $(CXXINCS)   -masm=intel
CFLAGS   = $(INCS)   -masm=intel
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ScreenSaver.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "ScreenSaver.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

sources/MatrixScreenSaver/graphics/graphics.o: sources/MatrixScreenSaver/graphics/graphics.cpp
	$(CPP) -c sources/MatrixScreenSaver/graphics/graphics.cpp -o sources/MatrixScreenSaver/graphics/graphics.o $(CXXFLAGS)

sources/MatrixScreenSaver/sound/sounds.o: sources/MatrixScreenSaver/sound/sounds.cpp
	$(CPP) -c sources/MatrixScreenSaver/sound/sounds.cpp -o sources/MatrixScreenSaver/sound/sounds.o $(CXXFLAGS)

sources/ScreenSaverShell/Shell.o: sources/ScreenSaverShell/Shell.cpp
	$(CPP) -c sources/ScreenSaverShell/Shell.cpp -o sources/ScreenSaverShell/Shell.o $(CXXFLAGS)
